-- Создание таблиц
CREATE TABLE IF NOT EXISTS basket_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity INTEGER NOT NULL,
    basket_id BIGINT,
    product_id BIGINT
);

CREATE TABLE IF NOT EXISTS baskets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image BLOB,
    name VARCHAR(255),
    price NUMERIC(38,2),
    product_id BIGINT,
    quantity INTEGER NOT NULL,
    order_id BIGINT
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    price NUMERIC(38,2),
    image BLOB
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    basket_id BIGINT
);

-- Удаление уникальных ограничений (если существуют)
ALTER TABLE baskets DROP CONSTRAINT IF EXISTS uk_basket_user;
ALTER TABLE users DROP CONSTRAINT IF EXISTS uk_user_basket;

-- Удаление внешних ключей (если существуют)
ALTER TABLE basket_item DROP CONSTRAINT IF EXISTS fk_basket_item_basket;
ALTER TABLE basket_item DROP CONSTRAINT IF EXISTS fk_basket_item_product;
ALTER TABLE baskets DROP CONSTRAINT IF EXISTS fk_basket_user;
ALTER TABLE order_items DROP CONSTRAINT IF EXISTS fk_order_item_order;
ALTER TABLE orders DROP CONSTRAINT IF EXISTS fk_order_user;
ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_user_basket;

-- Создание уникальных ограничений
ALTER TABLE baskets ADD CONSTRAINT uk_basket_user UNIQUE (user_id);
ALTER TABLE users ADD CONSTRAINT uk_user_basket UNIQUE (basket_id);

-- Создание внешних ключей
ALTER TABLE basket_item ADD CONSTRAINT fk_basket_item_basket
    FOREIGN KEY (basket_id) REFERENCES baskets(id);

ALTER TABLE basket_item ADD CONSTRAINT fk_basket_item_product
    FOREIGN KEY (product_id) REFERENCES products(id);

ALTER TABLE baskets ADD CONSTRAINT fk_basket_user
    FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE order_items ADD CONSTRAINT fk_order_item_order
    FOREIGN KEY (order_id) REFERENCES orders(id);

ALTER TABLE orders ADD CONSTRAINT fk_order_user
    FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE users ADD CONSTRAINT fk_user_basket
    FOREIGN KEY (basket_id) REFERENCES baskets(id);


