-- Создание таблиц
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(15,2),
    user_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    order_signature VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS balance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    amount NUMERIC(15,2)
);


-- create one user and basket
MERGE INTO balance (id, user_id, amount)
KEY (id)
VALUES (1, 1, 100000.00);


